#ifndef _QX_CP_EXPORT_H_
#define _QX_CP_EXPORT_H_

#ifdef _BUILDING_QX_CP
#define QX_CP_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_QX_CP
#define QX_CP_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_QX_CP

#ifdef _BUILDING_QX_CP
#define QX_REGISTER_HPP_CP_EXE     QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_CP_EXE     QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_QX_CP
#define QX_REGISTER_HPP_CP_EXE     QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_CP_EXE     QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_QX_CP

#endif // _QX_CP_EXPORT_H_
